const restaurantData = [
    {
        Id: 1,
        Name: "Jacob's Well Greek Orthodox Church",
        Category: "archaeological-site",
        Locationname: "676P+42F, Balata",
        Description: "Church",
        Longdescription: "Well in a Greek Orthodox church crypt where a Samaritan woman is said to have drawn water for Jesus.",
        Rating: 81,
        Isheartclicked: false,
        Ischeckclicked: false,
        Haveaparking: true,
        Suitableforpeoplewithspecialneeds: true,
        Foodsanddrinks: false,
        Internet: false,
        Therewillbephysicalactivity: false,
        Suitableforchildren: true,
        Suitableforoldpeople: true,
        Markets: false,
        Entrancefee: false,
        Antiquesouvenirsshop: false,
        Open247: true
    },
    {
        Id: 2,
        Name: "Heart Attack - جلطة",
        Category: "restaurant",
        Locationname: "رفيديا بجانب المستشفى العربي التخصصي, Nablus",
        Description: "Great food and atmosphere.",
        Longdescription: "Tasty & delicious food with generous portion size. The staff were very kind and polite. Highly recommend!",
        Rating: 82,
        Isheartclicked: false,
        Ischeckclicked: false,
        Vegetarianfood: false,
        Fastfood: true,
        Traditionaldishes: false,
        Grills: true,
        Seafood: false,
        Playgroundforchildren: false,
        Haveaparking: true,
        Suitableforpeoplewithspecialneeds: true,
        Suitableforoldpeople: false,
        Familyonly: false,
        Familysection: true,
        Homemadedishes: false,
        Open247: false
    },
    {
        Id: 3,
        Name: "Kaffeine Coffee House",
        Category: "cafe",
        Locationname: "Alaa' Eddin St., Rafedia, Nablus, Palestine",
        Description: "Historical significance in Nablus.",
        Longdescription: "Cosy bar like ambiance! Kaffeine is a wonderful place and one of the few places in this city to find amazing ambiance and just relaxing, self service place with normal prices compared to surrounding cafes, the taste in drinks might be a little off sometimes in rush hours and at night its mostly crowded so you may not ale to get a seat sometimes.",
        Rating: 83,
        Isheartclicked: true,
        Ischeckclicked: false,
        Sweets: true,
        Familyonly: false,
        Familysection: false,
        Suitableforworkandstudy: true,
        Showsmatches: false,
        Suitableforpeoplewithspecialneeds: true,
        Haveaparking: true,
        Cardgames: false,
        Open247: true
    },
    {
        Id: 4,
        Name: "مطعم ليمون ونعنع",
        Category: "restaurant",
        Locationname: "Nablus",
        Description: "restaurant",
        Longdescription: "Great restaurant, the halloumi salad was so good, we also tried Italian sandwich, burrito, and buffalo sandwich, and all of them were tasty. Very nice view, and fast service. Highly recommended.",
        Rating: 84,
        Isheartclicked: true,
        Ischeckclicked: false,
        Vegetarianfood: true,
        Fastfood: true,
        Traditionaldishes: true,
        Grills: true,
        Seafood: true,
        Playgroundforchildren: false,
        Haveaparking: true,
        Suitableforpeoplewithspecialneeds: true,
        Suitableforoldpeople: true,
        Familyonly: false,
        Familysection: true,
        Homemadedishes: true,
        Open247: false
    },
    {
        Id: 5,
        Name: "Tabshura",
        Category: "restaurant",
        Locationname: "66GF+8J4, Nablus",
        Description: "restaurant",
        Longdescription: "A beautiful place to relax.",
        Isheartclicked: true,
        Ischeckclicked: false,
        Vegetarianfood: true,
        Fastfood: true,
        Traditionaldishes: true,
        Grills: true,
        Seafood: false,
        Playgroundforchildren: false,
        Haveaparking: true,
        Suitableforpeoplewithspecialneeds: false,
        Suitableforoldpeople: true,
        Familyonly: false,
        Familysection: true,
        Homemadedishes: true,
        Open247: false
    },
    {
        Id: 6,
        Name: "Nablus Park",
        Category: "park",
        Locationname: "67G3+59Q, Nablus",
        Description: "Perfect for family outings.",
        Longdescription: "Very Lovely Park, Has A Lot Of Trees And Benches And Kids Playgrounds, But The Playgrounds Swings And Seesaws Are Broken And Not Safe.",
        Rating: 86,
        Isheartclicked: true,
        Ischeckclicked: true,
        Haveaparking: true,
        Suitableforpeoplewithspecialneeds: true,
        Suitableforoldpeople: true,
        Internet: false,
        Foodsanddrinks: true,
        Familyonly: false,
        Familysection: true,
        Entrancefee: false,
        Suitableforbarbecue: false,
        Playgroundforchildren: true,
        Open247: true
    },
    {
        Id: 7,
        Name: "المقبره الرومانية",
        Category: "archaeological-site",
        Locationname: "67F5+XV6, Nablus",
        Description: "Great atmosphere.",
        Longdescription: "Amazing historical place .. we must save and share .",
        Rating: 99,
        Isheartclicked: true,
        Ischeckclicked: true,
        Haveaparking: false,
        Suitableforpeoplewithspecialneeds: false,
        Foodsanddrinks: false,
        Internet: false,
        Therewillbephysicalactivity: true,
        Suitableforchildren: false,
        Suitableforoldpeople: false,
        Markets: true,
        Entrancefee: false,
        Antiquesouvenirsshop: false,
        Open247: true
    },
    {
        Id: 8,
        Name: "Joseph's Tomb",
        Category: "archaeological-site",
        Locationname: "677P+72F, Nablus",
        Description: "Historical significance in Nablus.",
        Longdescription: "Amazing place and good people",
        Rating: 88,
        Isheartclicked: false,
        Ischeckclicked: false,
        Haveaparking: false,
        Suitableforpeoplewithspecialneeds: false,
        Foodsanddrinks: false,
        Internet: false,
        Therewillbephysicalactivity: true,
        Suitableforchildren: false,
        Suitableforoldpeople: false,
        Markets: true,
        Entrancefee: false,
        Antiquesouvenirsshop: true,
        Open247: false
    },
    {
    Id: 9,
    Name: "Exit Escape Room",
    Category: "play-center",
    Locationname: "Al-Jamaa St.، Near Dream Mall،, Nablus",
    Description: "Escape Room",
    Longdescription: "I Love it !! It's just so entertaining, The puzzles in the games are a little difficult but fun, English translation is available for all games, and the staff is so lovely and helpful.",
    Rating: 93,
    Isheartclicked: true,
    Ischeckclicked: true,
    Haveaparking: true,
    Bowling: false,
    Billiard: false,
    Vr: false,
    Cardgames: false,
    Boardgames: true,
    Cyber: false,
    Suitableforpeoplewithspecialneeds: false,
    Foodsanddrinks: true,
    Open247: false
},
{
    Id: 10,
    Name: "Ottoman Clock Tower",
    Category: "archaeological-site",
    Locationname: "6796+HMH, Nablus",
    Description: "Exciting activities for all ages.",
    Longdescription: "The most beautiful scene in Nablus in the old city.",
    Rating: 94,
    Isheartclicked: true,
    Ischeckclicked: true,
    Haveaparking: false,
    Suitableforpeoplewithspecialneeds: true,
    Foodsanddrinks: true,
    Internet: false,
    Therewillbephysicalactivity: true,
    Suitableforchildren: true,
    Suitableforoldpeople: true,
    Markets: true,
    Entrancefee: false,
    Antiquesouvenirsshop: true,
    Open247: true
},
{
    Id: 11,
    Name: "Break Books Cafe",
    Category: "cafe",
    Locationname: "66GC+8CX, Nablus",
    Description: "A beautiful place to relax.",
    Longdescription: "The best place for relaxation and having good time and vibes",
    Rating: 90,
    Isheartclicked: true,
    Ischeckclicked: false,
    Sweets: true,
    Familyonly: false,
    Familysection: false,
    Suitableforworkandstudy: true,
    Showsmatches: false,
    Suitableforpeoplewithspecialneeds: true,
    Haveaparking: false,
    Cardgames: true,
    Open247: false
},
{
    Id: 12,
    Name: "مطعم كان يا مكان",
    Category: "restaurant",
    Locationname: "66FX+Q2W, Nablus",
    Description: "Great food and atmosphere.",
    Longdescription: "An absolutely wonderful place with all its details, all its services, and most importantly, amazing food. I recommend a visit, as the staff is beyond imagination and its atmosphere is sophistication, progress, and prosperity.",
    Rating: 97,
    Isheartclicked: false,
    Ischeckclicked: true,
    Vegetarianfood: true,
    Fastfood: true,
    Traditionaldishes: true,
    Grills: true,
    Seafood: true,
    Playgroundforchildren: true,
    Haveaparking: true,
    Suitableforpeoplewithspecialneeds: true,
    Suitableforoldpeople: true,
    Familyonly: false,
    Familysection: true,
    Homemadedishes: false,
    Open247: true
},
{
    Id: 13,
    Name: "Sama Nablus Park",
    Category: "park",
    Locationname: "67M3+HCM, جبل عيبال نابلس, Nablus",
    Description: "Historical significance in Nablus.",
    Longdescription: "Great place with a great view,You can see all Nablus from there,Clean place, and good place for families.",
    Rating: 78,
    Isheartclicked: true,
    Ischeckclicked: false,
    Haveaparking: true,
    Suitableforpeoplewithspecialneeds: true,
    Suitableforoldpeople: true,
    Internet: false,
    Foodsanddrinks: true,
    Familyonly: false,
    Familysection: true,
    Entrancefee: true,
    Suitableforbarbecue: true,
    Playgroundforchildren: true,
    Open247: true
},
{
    Id: 14,
    Name: "Fiction",
    Category: "play-center",
    Locationname: "66CR+V4, Nablus",
    Description: "Exciting activities for all ages.",
    Longdescription: "A great place to meet up with your friends and just have fun, the modern technology idea is amazing too 👏 …",
    Rating: 99,
    Isheartclicked: true,
    Ischeckclicked: true,
    Haveaparking: false,
    Bowling: false,
    Billiard: false,
    Vr: false,
    Cardgames: true,
    Boardgames: true,
    Cyber: false,
    Suitableforpeoplewithspecialneeds: true,
    Foodsanddrinks: true,
    Open247: true
},
{
    Id: 15,
    Name: "sabastia's Roman forum",
    Category: "archaeological-site",
    Locationname: "Location 20",
    Description: "Nice place to spend a day in.",
    Longdescription: "A wonderful Roman amphitheater that reflects an ancient and prosperous Roman civilization",
    Rating: 90,
    Isheartclicked: true,
    Ischeckclicked: true,
    Haveaparking: true,
    Suitableforpeoplewithspecialneeds: false,
    Foodsanddrinks: true,
    Internet: true,
    Therewillbephysicalactivity: true,
    Suitableforchildren: true,
    Suitableforoldpeople: true,
    Markets: true,
    Entrancefee: false,
    Antiquesouvenirsshop: true,
    Open247: true
},
{
    Id: 16,
    Name: "Tree House Cafe",
    Category: "cafe",
    Locationname: "  Nablus ,شارع النصر حارة الغرب",
    Description: "almost as if in a hobbit hole. Highly recommended.",
    Longdescription: "Wow what an absolutely amazing gem to find. A must visit. Such a beautiful location, wonderful coffee, and gracious staff.",
    Rating: 98,
    Isheartclicked: true,
    Ischeckclicked: true,
    Sweets: false,
    Familyonly: false,
    Familysection: true,
    Suitableforworkandstudy: false,
    Showsmatches: false,
    Suitableforpeoplewithspecialneeds: true,
    Haveaparking: false,
    Cardgames: true,
    Open247: false
},
{
    Id: 17,
    Name: "HULK Burger",
    Category: "restaurant",
    Locationname: "66GF+F5X, Nablus",
    Description: "a new way of serving burgers",
    Longdescription: "a nice place to eat with family",
    Rating: 83,
    Isheartclicked: false,
    Ischeckclicked: false,
    Vegetarianfood: true,
    Fastfood: true,
    Traditionaldishes: false,
    Grills: true,
    Seafood: false,
    Playgroundforchildren: false,
    Haveaparking: true,
    Suitableforpeoplewithspecialneeds: false,
    Suitableforoldpeople: true,
    Familyonly: false,
    Familysection: false,
    Homemadedishes: false,
    Open247: false
},
{
    Id: 18,
    Name: "منتزه العائلات",
    Category: "park",
    Locationname: "67F2+RW7, Nablus",
    Description: "Exciting activities for all ages.",
    Longdescription: "Nice place, u can spent a quiet evening, with nice music.",
    Rating: 84,
    Isheartclicked: true,
    Ischeckclicked: true,
    Haveaparking: true,
    Suitableforpeoplewithspecialneeds: true,
    Suitableforoldpeople: true,
    Internet: false,
    Foodsanddrinks: true,
    Familyonly: true,
    Familysection: false,
    Entrancefee: false,
    Suitableforbarbecue: false,
    Playgroundforchildren: true,
    Open247: false
},
{
    Id: 19,
    Name: "Laser Zone",
    Category: "play-center",
    Locationname: "67C7+W4X, faisal street nablus nablus, Nablus",
    Description: "A Great place to have some fun.",
    Longdescription: "Great place for team playing and a challenging experience.",
    Rating: 85,
    Isheartclicked: true,
    Ischeckclicked: false,
    Haveaparking: false,
    Bowling: false,
    Billiard: false,
    Vr: false,
    Cardgames: true,
    Boardgames: true,
    Cyber: true,
    Suitableforpeoplewithspecialneeds: false,
    Foodsanddrinks: true,
    Open247: false
},
{
    Id: 20,
    Name: "منتزه شلالات الباذان",
    Category: "park",
    Locationname: "Albathan street Wadi, al-Badhan",
    Description: "A beautiful place to relax.",
    Longdescription: "Very charming and picturesque natural areas, beautiful restaurants in a picturesque atmosphere, shops selling pottery, baskets and items of Palestinian heritage, a wonderful place to spend a fun and beautiful time with family and children.",
    Rating: 90,
    Isheartclicked: true,
    Ischeckclicked: true,
    Haveaparking: true,
    Suitableforpeoplewithspecialneeds: true,
    Suitableforoldpeople: true,
    Internet: true,
    Foodsanddrinks: true,
    Familyonly: false,
    Familysection: true,
    Entrancefee: true,
    Suitableforbarbecue: true,
    Playgroundforchildren: true,
    Open247: true
},
{
    Id: 21,
    Name: "Inferno Cyber Cafe",
    Category: "play-center",
    Locationname: "رفيديا",
    Description: "best place to show your gaming experience and skills.",
    Longdescription: "Best cyber cafe experience that you can have in Nablus, place is super clean and have great atmosphere and great employees, fast computers and they offer a lot of things that can't be found elsewhere.",
    Rating: 91,
    Isheartclicked: false,
    Ischeckclicked: false,
    Haveaparking: true,
    Bowling: false,
    Billiard: false,
    Vr: false,
    Cardgames: false,
    Boardgames: true,
    Cyber: true,
    Suitableforpeoplewithspecialneeds: true,
    Foodsanddrinks: true,
    Open247: true
},
{
    Id: 22,
    Name: "Maramia cafe ",
    Category: "cafe",
    Locationname: "66GC+Q92, Nablus",
    Description: "Great restaurant",
    Longdescription: "A luxurious restaurant, a wonderful staff, a spacious place with a beautiful view, first-class food.",
    Rating: 93,
    Isheartclicked: false,
    Ischeckclicked: false,
    Sweets: true,
    Familyonly: false,
    Familysection: true,
    Suitableforworkandstudy: false,
    Showsmatches: true,
    Suitableforpeoplewithspecialneeds: true,
    Haveaparking: true,
    Cardgames: false,
    Open247: false
},
{
    Id: 23,
    Name: "Bowling city",
    Category: "play-center",
    Locationname: "66QM+39H, Haifa Street, Nablus",
    Description: "Great place and nice atmosphere.",
    Longdescription: "a very good place to go have fun with family and friends.",
    Rating: 97,
    Isheartclicked: false,
    Ischeckclicked: false,
    Haveaparking: true,
    Bowling: true,
    Billiard: true,
    Vr: false,
    Cardgames: false,
    Boardgames: false,
    Cyber: false,
    Suitableforpeoplewithspecialneeds: false,
    Foodsanddrinks: true,
    Open247: false
},
{
    Id: 24,
    Name: "كافيه عطر الشام",
    Category: "cafe",
    Locationname: "66FX+R24, Nablus",
    Description: "Exciting place.",
    Longdescription: "Excellent food, reasonable prices, good service and beautiful view.",
    Rating: 66,
    Isheartclicked: false,
    Ischeckclicked: false,
    Sweets: true,
    Familyonly: false,
    Familysection: true,
    Suitableforworkandstudy: false,
    Showsmatches: false,
    Suitableforpeoplewithspecialneeds: true,
    Haveaparking: false,
    Cardgames: false,
    Open247: false
},
{
    Id: 25,
    Name: "إسعاد الطفولة",
    Category: "park",
    Locationname: "677H+H3V, Nablus",
    Description: "Great place to go with children.",
    Longdescription: "It has many beautiful places and safe children's games It is characterized by cleanliness and follow-up by those in charge of it.",
    Rating: 82,
    Isheartclicked: false,
    Ischeckclicked: false,
    Haveaparking: true,
    Suitableforpeoplewithspecialneeds: true,
    Suitableforoldpeople: true,
    Internet: false,
    Foodsanddrinks: true,
    Familyonly: true,
    Familysection: false,
    Entrancefee: true,
    Suitableforbarbecue: false,
    Playgroundforchildren: true,
    Open247: false
}
];
export default restaurantData; // Ensure this is how it's exported